project:
  type: book

book:
  title: "Playbook"
  author: "Fabio Spreafico"
  date: "19/02/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Foundations"
      chapters:
       - PracticalTheory.qmd
       - InstrumentPersonality.qmd
       - MarketAnalysis.qmd
    - part: "Strategies"
      chapters: 
        - strategy_summary.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
    papersize: "a4paper"
    geometry: 
       - top=25mm
       - bottom=25mm
       - left=20mm
       - right=20mm
    mainfont: "Segoe UI"

